# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Learning to See
owner: Logan Pendergrass
email: ljpendergrass@spu.edu
description: > # this means to ignore newlines until "baseurl:"
  The portfolio and thoughts of Logan Pendergrass, learning to see in new ways,
  one project at a time.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://loganpendergrass.com" # the base hostname & protocol for your site
twitter_username: ljp_206
github_username: ljpendergrass

# Build settings
markdown: kramdown
